trigger:
  branches:
    exclude:
    - "*"

pr: none

pool:
  vmImage: ubuntu-latest

variables:
- group: vgPowerPlantProduction
- name: resourceGroupName
  value: $(resourceGroupName)
- name: location
  value: $(location)

steps:
- script: |
    echo $(resourceGroupName)
    echo $(location)

- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnectionName)
    scriptType: "bash"
    scriptLocation: "inlineScript"
    inlineScript: |
      az group create --name $(resourceGroupName) --location "$(location)"

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: "Resource Group"
    azureResourceManagerConnection: $(serviceConnectionName)
    subscriptionId: $(subscriptionId)
    action: "Create Or Update Resource Group"
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: "URL of the file"
    csmFileLink: "https://raw.githubusercontent.com/pedromonteiroleite/PowerPlantProduction/main/.azure/bicep/main.bicep"
    deploymentMode: "Incremental"
    deploymentName: "DeployPipelineTemplate"
    overrideParameters: "-location $(location) -adminPassword $(adminPassword)"
